const data = {
    products: [
        {
            name : 'Free Shirt',
            slug : 'free-shirt',
            category: 'Shirts',
            image:'../public/images/product_1.webp',
            price:'',
            brand:'',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description : '',
          },
          {
            name : 'Slim Shirt',
            slug : 'slim-shirt',
            category: 'Shirts',
            image:'../public/images/product_2.webp',
            price:'',
            brand:'',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description : '',
          },
          {
            name : 'Free Pant',
            slug : 'free-pant',
            category: 'Pants',
            image:'../public/images/product_3.webp',
            price:'',
            brand:'',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description : '',
          },
          {
            name : 'Slim Pant',
            slug : 'slim-pant',
            category: 'Pants',
            image:'../public/images/product_4.webp',
            price:'',
            brand:'',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description : '',
          },
          {
            name : 'Free Shoes',
            slug : 'free-shoes',
            category: 'Shoes',
            image:'../public/images/product_5.webp',
            price:'',
            brand:'',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description : '',
          },
          {
            name : 'Black Shoes',
            slug : 'black-shoes',
            category: 'Shoes',
            image:'../public/images/product_6.webp',
            price:'',
            brand:'',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description : '',
          },
    

    ],
};

export default data;